
class DevConfig:
    TW_API_KEY = 'pC46hlWxiVSxQc3nPirF4ulh7'
    TW_API_SECRET = 'WQ0Gjw8zeMCCc5lL23XZbwrGaIKcf8HhhB2O03FMS1IP8YsmVs'
    TW_BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAPAdJAEAAAAA%2F16Xf%2FDINfTIk1jWxKxDHkm5SHI%3DU8h1wmmwIekrf3slSNoiNeKcLRrnOnTqL1SAufbRrhiyJ6mNCT'

    SYNC_DB = True
    TESTING = False
