import sys, os

import pytest

sys.path.append(os.path.realpath(os.path.dirname(__file__)+"/.."))

'''List of fixtures:
    :confirmed_user: Dictionary representation of a single User object (screen_name is `nickatak`) from Twitter's API.
    :confirmed_timeline: List of dictionaries (tweets) for the confirmed user above ^.
    :truncated_retweet_of_tracked_user: Dictionary representation of a single Tweet (retweet) from `nickatak` (retweeting themselves).
    
'''

@pytest.fixture
def truncated_retweet_of_tracked_user():
    # A known tweet (retweet) that's truncated. 
    return {
        "created_at": "Sun Apr 04 19:36:47 +0000 2021",
        "id": 1378793690425028610,
        "id_str": "1378793690425028610",
        "full_text": "RT @nickatak: assafddsdfasdaassafaafaffafsdfffsffadaafafasadfadsddsdsaaddfsadsasafffffasfsddfaasdsdadsfdfdddsaddaaddassfsfddassddasffddaafd…",
        "truncated": False,
        "display_text_range": [
            0,
            140
        ],
        "entities": {
            "hashtags": [],
            "symbols": [],
            "user_mentions": [
                {
                    "screen_name": "nickatak",
                    "name": "Nickatak",
                    "id": 1319269425522958336,
                    "id_str": "1319269425522958336",
                    "indices": [
                        3,
                        12
                    ]
                }
            ],
            "urls": []
        },
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
        "in_reply_to_status_id": None,
        "in_reply_to_status_id_str": None,
        "in_reply_to_user_id": None,
        "in_reply_to_user_id_str": None,
        "in_reply_to_screen_name": None,
        "user": {
            "id": 1319269425522958336,
            "id_str": "1319269425522958336",
            "name": "Nickatak",
            "screen_name": "nickatak",
            "location": "",
            "description": "",
            "url": None,
            "entities": {
                "description": {
                    "urls": []
                }
            },
            "protected": False,
            "followers_count": 0,
            "friends_count": 5,
            "listed_count": 0,
            "created_at": "Thu Oct 22 13:28:42 +0000 2020",
            "favourites_count": 1,
            "utc_offset": None,
            "time_zone": None,
            "geo_enabled": False,
            "verified": False,
            "statuses_count": 14,
            "lang": None,
            "contributors_enabled": False,
            "is_translator": False,
            "is_translation_enabled": False,
            "profile_background_color": "F5F8FA",
            "profile_background_image_url": None,
            "profile_background_image_url_https": None,
            "profile_background_tile": False,
            "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
            "profile_link_color": "1DA1F2",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": True,
            "has_extended_profile": True,
            "default_profile": True,
            "default_profile_image": False,
            "following": None,
            "follow_request_sent": None,
            "notifications": None,
            "translator_type": "none"
        },
        "geo": None,
        "coordinates": None,
        "place": None,
        "contributors": None,
        "retweeted_status": {
            "created_at": "Sun Apr 04 19:32:29 +0000 2021",
            "id": 1378792608890155010,
            "id_str": "1378792608890155010",
            "full_text": "assafddsdfasdaassafaafaffafsdfffsffadaafafasadfadsddsdsaaddfsadsasafffffasfsddfaasdsdadsfdfdddsaddaaddassfsfddassddasffddaafdadffafaaffadadfaaadsffsddaddfsddddsdddaaasasdaafaddddsf",
            "truncated": False,
            "display_text_range": [
                0,
                180
            ],
            "entities": {
                "hashtags": [],
                "symbols": [],
                "user_mentions": [],
                "urls": []
            },
            "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
            "in_reply_to_status_id": None,
            "in_reply_to_status_id_str": None,
            "in_reply_to_user_id": None,
            "in_reply_to_user_id_str": None,
            "in_reply_to_screen_name": None,
            "user": {
                "id": 1319269425522958336,
                "id_str": "1319269425522958336",
                "name": "Nickatak",
                "screen_name": "nickatak",
                "location": "",
                "description": "",
                "url": None,
                "entities": {
                    "description": {
                        "urls": []
                    }
                },
                "protected": False,
                "followers_count": 0,
                "friends_count": 5,
                "listed_count": 0,
                "created_at": "Thu Oct 22 13:28:42 +0000 2020",
                "favourites_count": 1,
                "utc_offset": None,
                "time_zone": None,
                "geo_enabled": False,
                "verified": False,
                "statuses_count": 14,
                "lang": None,
                "contributors_enabled": False,
                "is_translator": False,
                "is_translation_enabled": False,
                "profile_background_color": "F5F8FA",
                "profile_background_image_url": None,
                "profile_background_image_url_https": None,
                "profile_background_tile": False,
                "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
                "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
                "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
                "profile_link_color": "1DA1F2",
                "profile_sidebar_border_color": "C0DEED",
                "profile_sidebar_fill_color": "DDEEF6",
                "profile_text_color": "333333",
                "profile_use_background_image": True,
                "has_extended_profile": True,
                "default_profile": True,
                "default_profile_image": False,
                "following": None,
                "follow_request_sent": None,
                "notifications": None,
                "translator_type": "none"
            },
            "geo": None,
            "coordinates": None,
            "place": None,
            "contributors": None,
            "is_quote_status": False,
            "retweet_count": 1,
            "favorite_count": 0,
            "favorited": False,
            "retweeted": False,
            "lang": "tr"
        },
        "is_quote_status": False,
        "retweet_count": 1,
        "favorite_count": 0,
        "favorited": False,
        "retweeted": False,
        "lang": "tr"
    }

@pytest.fixture
def confirmed_user():
    # Expected returned user from sending a GET request to https://api.twitter.com/1.1/users/lookup.json?screen_name=nickatak as of 04/05/2021 @ 8:28 PM PST.
    return {
        "id": 1319269425522958336,
        "id_str": "1319269425522958336",
        "name": "Nickatak",
        "screen_name": "nickatak",
        "location": "",
        "description": "",
        "url": None,
        "entities": {
            "description": {
                "urls": []
            }
        },
        "protected": False,
        "followers_count": 0,
        "friends_count": 5,
        "listed_count": 0,
        "created_at": "Thu Oct 22 13:28:42 +0000 2020",
        "favourites_count": 1,
        "utc_offset": None,
        "time_zone": None,
        "geo_enabled": False,
        "verified": False,
        "statuses_count": 14,
        "lang": None,
        "status": {
            "created_at": "Sun Apr 04 19:47:14 +0000 2021",
            "id": 1378796322312970242,
            "id_str": "1378796322312970242",
            "text": "RT @nickatak: dssffdfsdfsadsfasfdssaasdasaffafssfsasdfddffafssffdsfafsdaddfdafafdasaddddasadasasafsdfdfaaffsffadssdsasffaaadsaffafsadsdafsa…",
            "truncated": False,
            "entities": {
                "hashtags": [],
                "symbols": [],
                "user_mentions": [
                    {
                        "screen_name": "nickatak",
                        "name": "Nickatak",
                        "id": 1319269425522958336,
                        "id_str": "1319269425522958336",
                        "indices": [
                            3,
                            12
                        ]
                    }
                ],
                "urls": []
            },
            "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
            "in_reply_to_status_id": None,
            "in_reply_to_status_id_str": None,
            "in_reply_to_user_id": None,
            "in_reply_to_user_id_str": None,
            "in_reply_to_screen_name": None,
            "geo": None,
            "coordinates": None,
            "place": None,
            "contributors": None,
            "retweeted_status": {
                "created_at": "Sun Apr 04 19:46:27 +0000 2021",
                "id": 1378796122399928320,
                "id_str": "1378796122399928320",
                "text": "dssffdfsdfsadsfasfdssaasdasaffafssfsasdfddffafssffdsfafsdaddfdafafdasaddddasadasasafsdfdfaaffsffadssdsasffaaadsaffa… https://t.co/gFFStpwWuo",
                "truncated": True,
                "entities": {
                    "hashtags": [],
                    "symbols": [],
                    "user_mentions": [],
                    "urls": [
                        {
                            "url": "https://t.co/gFFStpwWuo",
                            "expanded_url": "https://twitter.com/i/web/status/1378796122399928320",
                            "display_url": "twitter.com/i/web/status/1…",
                            "indices": [
                                117,
                                140
                            ]
                        }
                    ]
                },
                "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
                "in_reply_to_status_id": None,
                "in_reply_to_status_id_str": None,
                "in_reply_to_user_id": None,
                "in_reply_to_user_id_str": None,
                "in_reply_to_screen_name": None,
                "geo": None,
                "coordinates": None,
                "place": None,
                "contributors": None,
                "is_quote_status": False,
                "retweet_count": 1,
                "favorite_count": 0,
                "favorited": False,
                "retweeted": False,
                "lang": "tr"
            },
            "is_quote_status": False,
            "retweet_count": 1,
            "favorite_count": 0,
            "favorited": False,
            "retweeted": False,
            "lang": "tr"
        },
        "contributors_enabled": False,
        "is_translator": False,
        "is_translation_enabled": False,
        "profile_background_color": "F5F8FA",
        "profile_background_image_url": None,
        "profile_background_image_url_https": None,
        "profile_background_tile": False,
        "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
        "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
        "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
        "profile_link_color": "1DA1F2",
        "profile_sidebar_border_color": "C0DEED",
        "profile_sidebar_fill_color": "DDEEF6",
        "profile_text_color": "333333",
        "profile_use_background_image": True,
        "has_extended_profile": True,
        "default_profile": True,
        "default_profile_image": False,
        "following": None,
        "follow_request_sent": None,
        "notifications": None,
        "translator_type": "none"
    }

@pytest.fixture
def confirmed_timeline():
    # Expected returned tweets from sending a GET request to https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=nickatak&tweet_mode=extended as of 04/05/2021 @ 8:28 PM PST.
    return [
    {
        "created_at": "Sun Apr 04 19:47:14 +0000 2021",
        "id": 1378796322312970242,
        "id_str": "1378796322312970242",
        "full_text": "RT @nickatak: dssffdfsdfsadsfasfdssaasdasaffafssfsasdfddffafssffdsfafsdaddfdafafdasaddddasadasasafsdfdfaaffsffadssdsasffaaadsaffafsadsdafsa…",
        "truncated": False,
        "display_text_range": [
            0,
            140
        ],
        "entities": {
            "hashtags": [],
            "symbols": [],
            "user_mentions": [
                {
                    "screen_name": "nickatak",
                    "name": "Nickatak",
                    "id": 1319269425522958336,
                    "id_str": "1319269425522958336",
                    "indices": [
                        3,
                        12
                    ]
                }
            ],
            "urls": []
        },
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
        "in_reply_to_status_id": None,
        "in_reply_to_status_id_str": None,
        "in_reply_to_user_id": None,
        "in_reply_to_user_id_str": None,
        "in_reply_to_screen_name": None,
        "user": {
            "id": 1319269425522958336,
            "id_str": "1319269425522958336",
            "name": "Nickatak",
            "screen_name": "nickatak",
            "location": "",
            "description": "",
            "url": None,
            "entities": {
                "description": {
                    "urls": []
                }
            },
            "protected": False,
            "followers_count": 0,
            "friends_count": 5,
            "listed_count": 0,
            "created_at": "Thu Oct 22 13:28:42 +0000 2020",
            "favourites_count": 1,
            "utc_offset": None,
            "time_zone": None,
            "geo_enabled": False,
            "verified": False,
            "statuses_count": 14,
            "lang": None,
            "contributors_enabled": False,
            "is_translator": False,
            "is_translation_enabled": False,
            "profile_background_color": "F5F8FA",
            "profile_background_image_url": None,
            "profile_background_image_url_https": None,
            "profile_background_tile": False,
            "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
            "profile_link_color": "1DA1F2",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": True,
            "has_extended_profile": True,
            "default_profile": True,
            "default_profile_image": False,
            "following": None,
            "follow_request_sent": None,
            "notifications": None,
            "translator_type": "none"
        },
        "geo": None,
        "coordinates": None,
        "place": None,
        "contributors": None,
        "retweeted_status": {
            "created_at": "Sun Apr 04 19:46:27 +0000 2021",
            "id": 1378796122399928320,
            "id_str": "1378796122399928320",
            "full_text": "dssffdfsdfsadsfasfdssaasdasaffafssfsasdfddffafssffdsfafsdaddfdafafdasaddddasadasasafsdfdfaaffsffadssdsasffaaadsaffafsadsdafsafsaafdfadfffffdaasaadfaasfssfssdadaasaafsffsadffssaafdadfsaafadsffsafdsaafdsadssdsffsadafddsfaadffaasfafsffsadasafafasdaasafafdddfdsssafddsfasdsadassfdsad",
            "truncated": False,
            "display_text_range": [
                0,
                279
            ],
            "entities": {
                "hashtags": [],
                "symbols": [],
                "user_mentions": [],
                "urls": []
            },
            "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
            "in_reply_to_status_id": None,
            "in_reply_to_status_id_str": None,
            "in_reply_to_user_id": None,
            "in_reply_to_user_id_str": None,
            "in_reply_to_screen_name": None,
            "user": {
                "id": 1319269425522958336,
                "id_str": "1319269425522958336",
                "name": "Nickatak",
                "screen_name": "nickatak",
                "location": "",
                "description": "",
                "url": None,
                "entities": {
                    "description": {
                        "urls": []
                    }
                },
                "protected": False,
                "followers_count": 0,
                "friends_count": 5,
                "listed_count": 0,
                "created_at": "Thu Oct 22 13:28:42 +0000 2020",
                "favourites_count": 1,
                "utc_offset": None,
                "time_zone": None,
                "geo_enabled": False,
                "verified": False,
                "statuses_count": 14,
                "lang": None,
                "contributors_enabled": False,
                "is_translator": False,
                "is_translation_enabled": False,
                "profile_background_color": "F5F8FA",
                "profile_background_image_url": None,
                "profile_background_image_url_https": None,
                "profile_background_tile": False,
                "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
                "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
                "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
                "profile_link_color": "1DA1F2",
                "profile_sidebar_border_color": "C0DEED",
                "profile_sidebar_fill_color": "DDEEF6",
                "profile_text_color": "333333",
                "profile_use_background_image": True,
                "has_extended_profile": True,
                "default_profile": True,
                "default_profile_image": False,
                "following": None,
                "follow_request_sent": None,
                "notifications": None,
                "translator_type": "none"
            },
            "geo": None,
            "coordinates": None,
            "place": None,
            "contributors": None,
            "is_quote_status": False,
            "retweet_count": 1,
            "favorite_count": 0,
            "favorited": False,
            "retweeted": False,
            "lang": "tr"
        },
        "is_quote_status": False,
        "retweet_count": 1,
        "favorite_count": 0,
        "favorited": False,
        "retweeted": False,
        "lang": "tr"
    },
    {
        "created_at": "Sun Apr 04 19:46:27 +0000 2021",
        "id": 1378796122399928320,
        "id_str": "1378796122399928320",
        "full_text": "dssffdfsdfsadsfasfdssaasdasaffafssfsasdfddffafssffdsfafsdaddfdafafdasaddddasadasasafsdfdfaaffsffadssdsasffaaadsaffafsadsdafsafsaafdfadfffffdaasaadfaasfssfssdadaasaafsffsadffssaafdadfsaafadsffsafdsaafdsadssdsffsadafddsfaadffaasfafsffsadasafafasdaasafafdddfdsssafddsfasdsadassfdsad",
        "truncated": False,
        "display_text_range": [
            0,
            279
        ],
        "entities": {
            "hashtags": [],
            "symbols": [],
            "user_mentions": [],
            "urls": []
        },
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
        "in_reply_to_status_id": None,
        "in_reply_to_status_id_str": None,
        "in_reply_to_user_id": None,
        "in_reply_to_user_id_str": None,
        "in_reply_to_screen_name": None,
        "user": {
            "id": 1319269425522958336,
            "id_str": "1319269425522958336",
            "name": "Nickatak",
            "screen_name": "nickatak",
            "location": "",
            "description": "",
            "url": None,
            "entities": {
                "description": {
                    "urls": []
                }
            },
            "protected": False,
            "followers_count": 0,
            "friends_count": 5,
            "listed_count": 0,
            "created_at": "Thu Oct 22 13:28:42 +0000 2020",
            "favourites_count": 1,
            "utc_offset": None,
            "time_zone": None,
            "geo_enabled": False,
            "verified": False,
            "statuses_count": 14,
            "lang": None,
            "contributors_enabled": False,
            "is_translator": False,
            "is_translation_enabled": False,
            "profile_background_color": "F5F8FA",
            "profile_background_image_url": None,
            "profile_background_image_url_https": None,
            "profile_background_tile": False,
            "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
            "profile_link_color": "1DA1F2",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": True,
            "has_extended_profile": True,
            "default_profile": True,
            "default_profile_image": False,
            "following": None,
            "follow_request_sent": None,
            "notifications": None,
            "translator_type": "none"
        },
        "geo": None,
        "coordinates": None,
        "place": None,
        "contributors": None,
        "is_quote_status": False,
        "retweet_count": 1,
        "favorite_count": 0,
        "favorited": False,
        "retweeted": False,
        "lang": "tr"
    },
    {
        "created_at": "Sun Apr 04 19:36:47 +0000 2021",
        "id": 1378793690425028610,
        "id_str": "1378793690425028610",
        "full_text": "RT @nickatak: assafddsdfasdaassafaafaffafsdfffsffadaafafasadfadsddsdsaaddfsadsasafffffasfsddfaasdsdadsfdfdddsaddaaddassfsfddassddasffddaafd…",
        "truncated": False,
        "display_text_range": [
            0,
            140
        ],
        "entities": {
            "hashtags": [],
            "symbols": [],
            "user_mentions": [
                {
                    "screen_name": "nickatak",
                    "name": "Nickatak",
                    "id": 1319269425522958336,
                    "id_str": "1319269425522958336",
                    "indices": [
                        3,
                        12
                    ]
                }
            ],
            "urls": []
        },
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
        "in_reply_to_status_id": None,
        "in_reply_to_status_id_str": None,
        "in_reply_to_user_id": None,
        "in_reply_to_user_id_str": None,
        "in_reply_to_screen_name": None,
        "user": {
            "id": 1319269425522958336,
            "id_str": "1319269425522958336",
            "name": "Nickatak",
            "screen_name": "nickatak",
            "location": "",
            "description": "",
            "url": None,
            "entities": {
                "description": {
                    "urls": []
                }
            },
            "protected": False,
            "followers_count": 0,
            "friends_count": 5,
            "listed_count": 0,
            "created_at": "Thu Oct 22 13:28:42 +0000 2020",
            "favourites_count": 1,
            "utc_offset": None,
            "time_zone": None,
            "geo_enabled": False,
            "verified": False,
            "statuses_count": 14,
            "lang": None,
            "contributors_enabled": False,
            "is_translator": False,
            "is_translation_enabled": False,
            "profile_background_color": "F5F8FA",
            "profile_background_image_url": None,
            "profile_background_image_url_https": None,
            "profile_background_tile": False,
            "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
            "profile_link_color": "1DA1F2",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": True,
            "has_extended_profile": True,
            "default_profile": True,
            "default_profile_image": False,
            "following": None,
            "follow_request_sent": None,
            "notifications": None,
            "translator_type": "none"
        },
        "geo": None,
        "coordinates": None,
        "place": None,
        "contributors": None,
        "retweeted_status": {
            "created_at": "Sun Apr 04 19:32:29 +0000 2021",
            "id": 1378792608890155010,
            "id_str": "1378792608890155010",
            "full_text": "assafddsdfasdaassafaafaffafsdfffsffadaafafasadfadsddsdsaaddfsadsasafffffasfsddfaasdsdadsfdfdddsaddaaddassfsfddassddasffddaafdadffafaaffadadfaaadsffsddaddfsddddsdddaaasasdaafaddddsf",
            "truncated": False,
            "display_text_range": [
                0,
                180
            ],
            "entities": {
                "hashtags": [],
                "symbols": [],
                "user_mentions": [],
                "urls": []
            },
            "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
            "in_reply_to_status_id": None,
            "in_reply_to_status_id_str": None,
            "in_reply_to_user_id": None,
            "in_reply_to_user_id_str": None,
            "in_reply_to_screen_name": None,
            "user": {
                "id": 1319269425522958336,
                "id_str": "1319269425522958336",
                "name": "Nickatak",
                "screen_name": "nickatak",
                "location": "",
                "description": "",
                "url": None,
                "entities": {
                    "description": {
                        "urls": []
                    }
                },
                "protected": False,
                "followers_count": 0,
                "friends_count": 5,
                "listed_count": 0,
                "created_at": "Thu Oct 22 13:28:42 +0000 2020",
                "favourites_count": 1,
                "utc_offset": None,
                "time_zone": None,
                "geo_enabled": False,
                "verified": False,
                "statuses_count": 14,
                "lang": None,
                "contributors_enabled": False,
                "is_translator": False,
                "is_translation_enabled": False,
                "profile_background_color": "F5F8FA",
                "profile_background_image_url": None,
                "profile_background_image_url_https": None,
                "profile_background_tile": False,
                "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
                "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
                "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
                "profile_link_color": "1DA1F2",
                "profile_sidebar_border_color": "C0DEED",
                "profile_sidebar_fill_color": "DDEEF6",
                "profile_text_color": "333333",
                "profile_use_background_image": True,
                "has_extended_profile": True,
                "default_profile": True,
                "default_profile_image": False,
                "following": None,
                "follow_request_sent": None,
                "notifications": None,
                "translator_type": "none"
            },
            "geo": None,
            "coordinates": None,
            "place": None,
            "contributors": None,
            "is_quote_status": False,
            "retweet_count": 1,
            "favorite_count": 0,
            "favorited": False,
            "retweeted": False,
            "lang": "tr"
        },
        "is_quote_status": False,
        "retweet_count": 1,
        "favorite_count": 0,
        "favorited": False,
        "retweeted": False,
        "lang": "tr"
    },
    {
        "created_at": "Sun Apr 04 19:32:29 +0000 2021",
        "id": 1378792608890155010,
        "id_str": "1378792608890155010",
        "full_text": "assafddsdfasdaassafaafaffafsdfffsffadaafafasadfadsddsdsaaddfsadsasafffffasfsddfaasdsdadsfdfdddsaddaaddassfsfddassddasffddaafdadffafaaffadadfaaadsffsddaddfsddddsdddaaasasdaafaddddsf",
        "truncated": False,
        "display_text_range": [
            0,
            180
        ],
        "entities": {
            "hashtags": [],
            "symbols": [],
            "user_mentions": [],
            "urls": []
        },
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
        "in_reply_to_status_id": None,
        "in_reply_to_status_id_str": None,
        "in_reply_to_user_id": None,
        "in_reply_to_user_id_str": None,
        "in_reply_to_screen_name": None,
        "user": {
            "id": 1319269425522958336,
            "id_str": "1319269425522958336",
            "name": "Nickatak",
            "screen_name": "nickatak",
            "location": "",
            "description": "",
            "url": None,
            "entities": {
                "description": {
                    "urls": []
                }
            },
            "protected": False,
            "followers_count": 0,
            "friends_count": 5,
            "listed_count": 0,
            "created_at": "Thu Oct 22 13:28:42 +0000 2020",
            "favourites_count": 1,
            "utc_offset": None,
            "time_zone": None,
            "geo_enabled": False,
            "verified": False,
            "statuses_count": 14,
            "lang": None,
            "contributors_enabled": False,
            "is_translator": False,
            "is_translation_enabled": False,
            "profile_background_color": "F5F8FA",
            "profile_background_image_url": None,
            "profile_background_image_url_https": None,
            "profile_background_tile": False,
            "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
            "profile_link_color": "1DA1F2",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": True,
            "has_extended_profile": True,
            "default_profile": True,
            "default_profile_image": False,
            "following": None,
            "follow_request_sent": None,
            "notifications": None,
            "translator_type": "none"
        },
        "geo": None,
        "coordinates": None,
        "place": None,
        "contributors": None,
        "is_quote_status": False,
        "retweet_count": 1,
        "favorite_count": 0,
        "favorited": False,
        "retweeted": False,
        "lang": "tr"
    },
    {
        "created_at": "Fri Mar 26 08:04:24 +0000 2021",
        "id": 1375357956171001857,
        "id_str": "1375357956171001857",
        "full_text": "test3",
        "truncated": False,
        "display_text_range": [
            0,
            5
        ],
        "entities": {
            "hashtags": [],
            "symbols": [],
            "user_mentions": [],
            "urls": []
        },
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
        "in_reply_to_status_id": None,
        "in_reply_to_status_id_str": None,
        "in_reply_to_user_id": None,
        "in_reply_to_user_id_str": None,
        "in_reply_to_screen_name": None,
        "user": {
            "id": 1319269425522958336,
            "id_str": "1319269425522958336",
            "name": "Nickatak",
            "screen_name": "nickatak",
            "location": "",
            "description": "",
            "url": None,
            "entities": {
                "description": {
                    "urls": []
                }
            },
            "protected": False,
            "followers_count": 0,
            "friends_count": 5,
            "listed_count": 0,
            "created_at": "Thu Oct 22 13:28:42 +0000 2020",
            "favourites_count": 1,
            "utc_offset": None,
            "time_zone": None,
            "geo_enabled": False,
            "verified": False,
            "statuses_count": 14,
            "lang": None,
            "contributors_enabled": False,
            "is_translator": False,
            "is_translation_enabled": False,
            "profile_background_color": "F5F8FA",
            "profile_background_image_url": None,
            "profile_background_image_url_https": None,
            "profile_background_tile": False,
            "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
            "profile_link_color": "1DA1F2",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": True,
            "has_extended_profile": True,
            "default_profile": True,
            "default_profile_image": False,
            "following": None,
            "follow_request_sent": None,
            "notifications": None,
            "translator_type": "none"
        },
        "geo": None,
        "coordinates": None,
        "place": None,
        "contributors": None,
        "is_quote_status": False,
        "retweet_count": 0,
        "favorite_count": 0,
        "favorited": False,
        "retweeted": False,
        "lang": "en"
    },
    {
        "created_at": "Fri Mar 26 07:25:41 +0000 2021",
        "id": 1375348212832235521,
        "id_str": "1375348212832235521",
        "full_text": "Tester2",
        "truncated": False,
        "display_text_range": [
            0,
            7
        ],
        "entities": {
            "hashtags": [],
            "symbols": [],
            "user_mentions": [],
            "urls": []
        },
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
        "in_reply_to_status_id": None,
        "in_reply_to_status_id_str": None,
        "in_reply_to_user_id": None,
        "in_reply_to_user_id_str": None,
        "in_reply_to_screen_name": None,
        "user": {
            "id": 1319269425522958336,
            "id_str": "1319269425522958336",
            "name": "Nickatak",
            "screen_name": "nickatak",
            "location": "",
            "description": "",
            "url": None,
            "entities": {
                "description": {
                    "urls": []
                }
            },
            "protected": False,
            "followers_count": 0,
            "friends_count": 5,
            "listed_count": 0,
            "created_at": "Thu Oct 22 13:28:42 +0000 2020",
            "favourites_count": 1,
            "utc_offset": None,
            "time_zone": None,
            "geo_enabled": False,
            "verified": False,
            "statuses_count": 14,
            "lang": None,
            "contributors_enabled": False,
            "is_translator": False,
            "is_translation_enabled": False,
            "profile_background_color": "F5F8FA",
            "profile_background_image_url": None,
            "profile_background_image_url_https": None,
            "profile_background_tile": False,
            "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
            "profile_link_color": "1DA1F2",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": True,
            "has_extended_profile": True,
            "default_profile": True,
            "default_profile_image": False,
            "following": None,
            "follow_request_sent": None,
            "notifications": None,
            "translator_type": "none"
        },
        "geo": None,
        "coordinates": None,
        "place": None,
        "contributors": None,
        "is_quote_status": False,
        "retweet_count": 0,
        "favorite_count": 0,
        "favorited": False,
        "retweeted": False,
        "lang": "en"
    },
    {
        "created_at": "Thu Mar 25 18:25:33 +0000 2021",
        "id": 1375151887985434626,
        "id_str": "1375151887985434626",
        "full_text": "hi fulli",
        "truncated": False,
        "display_text_range": [
            0,
            8
        ],
        "entities": {
            "hashtags": [],
            "symbols": [],
            "user_mentions": [],
            "urls": []
        },
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
        "in_reply_to_status_id": None,
        "in_reply_to_status_id_str": None,
        "in_reply_to_user_id": None,
        "in_reply_to_user_id_str": None,
        "in_reply_to_screen_name": None,
        "user": {
            "id": 1319269425522958336,
            "id_str": "1319269425522958336",
            "name": "Nickatak",
            "screen_name": "nickatak",
            "location": "",
            "description": "",
            "url": None,
            "entities": {
                "description": {
                    "urls": []
                }
            },
            "protected": False,
            "followers_count": 0,
            "friends_count": 5,
            "listed_count": 0,
            "created_at": "Thu Oct 22 13:28:42 +0000 2020",
            "favourites_count": 1,
            "utc_offset": None,
            "time_zone": None,
            "geo_enabled": False,
            "verified": False,
            "statuses_count": 14,
            "lang": None,
            "contributors_enabled": False,
            "is_translator": False,
            "is_translation_enabled": False,
            "profile_background_color": "F5F8FA",
            "profile_background_image_url": None,
            "profile_background_image_url_https": None,
            "profile_background_tile": False,
            "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
            "profile_link_color": "1DA1F2",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": True,
            "has_extended_profile": True,
            "default_profile": True,
            "default_profile_image": False,
            "following": None,
            "follow_request_sent": None,
            "notifications": None,
            "translator_type": "none"
        },
        "geo": None,
        "coordinates": None,
        "place": None,
        "contributors": None,
        "is_quote_status": False,
        "retweet_count": 0,
        "favorite_count": 0,
        "favorited": False,
        "retweeted": False,
        "lang": "en"
    },
    {
        "created_at": "Thu Mar 25 18:22:54 +0000 2021",
        "id": 1375151217945419777,
        "id_str": "1375151217945419777",
        "full_text": "test 6",
        "truncated": False,
        "display_text_range": [
            0,
            6
        ],
        "entities": {
            "hashtags": [],
            "symbols": [],
            "user_mentions": [],
            "urls": []
        },
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
        "in_reply_to_status_id": None,
        "in_reply_to_status_id_str": None,
        "in_reply_to_user_id": None,
        "in_reply_to_user_id_str": None,
        "in_reply_to_screen_name": None,
        "user": {
            "id": 1319269425522958336,
            "id_str": "1319269425522958336",
            "name": "Nickatak",
            "screen_name": "nickatak",
            "location": "",
            "description": "",
            "url": None,
            "entities": {
                "description": {
                    "urls": []
                }
            },
            "protected": False,
            "followers_count": 0,
            "friends_count": 5,
            "listed_count": 0,
            "created_at": "Thu Oct 22 13:28:42 +0000 2020",
            "favourites_count": 1,
            "utc_offset": None,
            "time_zone": None,
            "geo_enabled": False,
            "verified": False,
            "statuses_count": 14,
            "lang": None,
            "contributors_enabled": False,
            "is_translator": False,
            "is_translation_enabled": False,
            "profile_background_color": "F5F8FA",
            "profile_background_image_url": None,
            "profile_background_image_url_https": None,
            "profile_background_tile": False,
            "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
            "profile_link_color": "1DA1F2",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": True,
            "has_extended_profile": True,
            "default_profile": True,
            "default_profile_image": False,
            "following": None,
            "follow_request_sent": None,
            "notifications": None,
            "translator_type": "none"
        },
        "geo": None,
        "coordinates": None,
        "place": None,
        "contributors": None,
        "is_quote_status": False,
        "retweet_count": 0,
        "favorite_count": 0,
        "favorited": False,
        "retweeted": False,
        "lang": "en"
    },
    {
        "created_at": "Thu Mar 25 18:17:18 +0000 2021",
        "id": 1375149812253790210,
        "id_str": "1375149812253790210",
        "full_text": "Test 5",
        "truncated": False,
        "display_text_range": [
            0,
            6
        ],
        "entities": {
            "hashtags": [],
            "symbols": [],
            "user_mentions": [],
            "urls": []
        },
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
        "in_reply_to_status_id": None,
        "in_reply_to_status_id_str": None,
        "in_reply_to_user_id": None,
        "in_reply_to_user_id_str": None,
        "in_reply_to_screen_name": None,
        "user": {
            "id": 1319269425522958336,
            "id_str": "1319269425522958336",
            "name": "Nickatak",
            "screen_name": "nickatak",
            "location": "",
            "description": "",
            "url": None,
            "entities": {
                "description": {
                    "urls": []
                }
            },
            "protected": False,
            "followers_count": 0,
            "friends_count": 5,
            "listed_count": 0,
            "created_at": "Thu Oct 22 13:28:42 +0000 2020",
            "favourites_count": 1,
            "utc_offset": None,
            "time_zone": None,
            "geo_enabled": False,
            "verified": False,
            "statuses_count": 14,
            "lang": None,
            "contributors_enabled": False,
            "is_translator": False,
            "is_translation_enabled": False,
            "profile_background_color": "F5F8FA",
            "profile_background_image_url": None,
            "profile_background_image_url_https": None,
            "profile_background_tile": False,
            "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
            "profile_link_color": "1DA1F2",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": True,
            "has_extended_profile": True,
            "default_profile": True,
            "default_profile_image": False,
            "following": None,
            "follow_request_sent": None,
            "notifications": None,
            "translator_type": "none"
        },
        "geo": None,
        "coordinates": None,
        "place": None,
        "contributors": None,
        "is_quote_status": False,
        "retweet_count": 0,
        "favorite_count": 0,
        "favorited": False,
        "retweeted": False,
        "lang": "en"
    },
    {
        "created_at": "Thu Mar 25 10:02:03 +0000 2021",
        "id": 1375025174970392576,
        "id_str": "1375025174970392576",
        "full_text": "test 4",
        "truncated": False,
        "display_text_range": [
            0,
            6
        ],
        "entities": {
            "hashtags": [],
            "symbols": [],
            "user_mentions": [],
            "urls": []
        },
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
        "in_reply_to_status_id": None,
        "in_reply_to_status_id_str": None,
        "in_reply_to_user_id": None,
        "in_reply_to_user_id_str": None,
        "in_reply_to_screen_name": None,
        "user": {
            "id": 1319269425522958336,
            "id_str": "1319269425522958336",
            "name": "Nickatak",
            "screen_name": "nickatak",
            "location": "",
            "description": "",
            "url": None,
            "entities": {
                "description": {
                    "urls": []
                }
            },
            "protected": False,
            "followers_count": 0,
            "friends_count": 5,
            "listed_count": 0,
            "created_at": "Thu Oct 22 13:28:42 +0000 2020",
            "favourites_count": 1,
            "utc_offset": None,
            "time_zone": None,
            "geo_enabled": False,
            "verified": False,
            "statuses_count": 14,
            "lang": None,
            "contributors_enabled": False,
            "is_translator": False,
            "is_translation_enabled": False,
            "profile_background_color": "F5F8FA",
            "profile_background_image_url": None,
            "profile_background_image_url_https": None,
            "profile_background_tile": False,
            "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
            "profile_link_color": "1DA1F2",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": True,
            "has_extended_profile": True,
            "default_profile": True,
            "default_profile_image": False,
            "following": None,
            "follow_request_sent": None,
            "notifications": None,
            "translator_type": "none"
        },
        "geo": None,
        "coordinates": None,
        "place": None,
        "contributors": None,
        "is_quote_status": False,
        "retweet_count": 0,
        "favorite_count": 0,
        "favorited": False,
        "retweeted": False,
        "lang": "en"
    },
    {
        "created_at": "Thu Mar 25 06:53:00 +0000 2021",
        "id": 1374977602285314049,
        "id_str": "1374977602285314049",
        "full_text": "test tweet 3",
        "truncated": False,
        "display_text_range": [
            0,
            12
        ],
        "entities": {
            "hashtags": [],
            "symbols": [],
            "user_mentions": [],
            "urls": []
        },
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
        "in_reply_to_status_id": None,
        "in_reply_to_status_id_str": None,
        "in_reply_to_user_id": None,
        "in_reply_to_user_id_str": None,
        "in_reply_to_screen_name": None,
        "user": {
            "id": 1319269425522958336,
            "id_str": "1319269425522958336",
            "name": "Nickatak",
            "screen_name": "nickatak",
            "location": "",
            "description": "",
            "url": None,
            "entities": {
                "description": {
                    "urls": []
                }
            },
            "protected": False,
            "followers_count": 0,
            "friends_count": 5,
            "listed_count": 0,
            "created_at": "Thu Oct 22 13:28:42 +0000 2020",
            "favourites_count": 1,
            "utc_offset": None,
            "time_zone": None,
            "geo_enabled": False,
            "verified": False,
            "statuses_count": 14,
            "lang": None,
            "contributors_enabled": False,
            "is_translator": False,
            "is_translation_enabled": False,
            "profile_background_color": "F5F8FA",
            "profile_background_image_url": None,
            "profile_background_image_url_https": None,
            "profile_background_tile": False,
            "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
            "profile_link_color": "1DA1F2",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": True,
            "has_extended_profile": True,
            "default_profile": True,
            "default_profile_image": False,
            "following": None,
            "follow_request_sent": None,
            "notifications": None,
            "translator_type": "none"
        },
        "geo": None,
        "coordinates": None,
        "place": None,
        "contributors": None,
        "is_quote_status": False,
        "retweet_count": 0,
        "favorite_count": 0,
        "favorited": False,
        "retweeted": False,
        "lang": "fr"
    },
    {
        "created_at": "Thu Mar 25 05:58:10 +0000 2021",
        "id": 1374963801494155266,
        "id_str": "1374963801494155266",
        "full_text": "test tweet 2",
        "truncated": False,
        "display_text_range": [
            0,
            12
        ],
        "entities": {
            "hashtags": [],
            "symbols": [],
            "user_mentions": [],
            "urls": []
        },
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
        "in_reply_to_status_id": None,
        "in_reply_to_status_id_str": None,
        "in_reply_to_user_id": None,
        "in_reply_to_user_id_str": None,
        "in_reply_to_screen_name": None,
        "user": {
            "id": 1319269425522958336,
            "id_str": "1319269425522958336",
            "name": "Nickatak",
            "screen_name": "nickatak",
            "location": "",
            "description": "",
            "url": None,
            "entities": {
                "description": {
                    "urls": []
                }
            },
            "protected": False,
            "followers_count": 0,
            "friends_count": 5,
            "listed_count": 0,
            "created_at": "Thu Oct 22 13:28:42 +0000 2020",
            "favourites_count": 1,
            "utc_offset": None,
            "time_zone": None,
            "geo_enabled": False,
            "verified": False,
            "statuses_count": 14,
            "lang": None,
            "contributors_enabled": False,
            "is_translator": False,
            "is_translation_enabled": False,
            "profile_background_color": "F5F8FA",
            "profile_background_image_url": None,
            "profile_background_image_url_https": None,
            "profile_background_tile": False,
            "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
            "profile_link_color": "1DA1F2",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": True,
            "has_extended_profile": True,
            "default_profile": True,
            "default_profile_image": False,
            "following": None,
            "follow_request_sent": None,
            "notifications": None,
            "translator_type": "none"
        },
        "geo": None,
        "coordinates": None,
        "place": None,
        "contributors": None,
        "is_quote_status": False,
        "retweet_count": 0,
        "favorite_count": 0,
        "favorited": False,
        "retweeted": False,
        "lang": "fr"
    },
    {
        "created_at": "Wed Mar 24 20:05:28 +0000 2021",
        "id": 1374814643571449858,
        "id_str": "1374814643571449858",
        "full_text": "Test tweet 1",
        "truncated": False,
        "display_text_range": [
            0,
            12
        ],
        "entities": {
            "hashtags": [],
            "symbols": [],
            "user_mentions": [],
            "urls": []
        },
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
        "in_reply_to_status_id": None,
        "in_reply_to_status_id_str": None,
        "in_reply_to_user_id": None,
        "in_reply_to_user_id_str": None,
        "in_reply_to_screen_name": None,
        "user": {
            "id": 1319269425522958336,
            "id_str": "1319269425522958336",
            "name": "Nickatak",
            "screen_name": "nickatak",
            "location": "",
            "description": "",
            "url": None,
            "entities": {
                "description": {
                    "urls": []
                }
            },
            "protected": False,
            "followers_count": 0,
            "friends_count": 5,
            "listed_count": 0,
            "created_at": "Thu Oct 22 13:28:42 +0000 2020",
            "favourites_count": 1,
            "utc_offset": None,
            "time_zone": None,
            "geo_enabled": False,
            "verified": False,
            "statuses_count": 14,
            "lang": None,
            "contributors_enabled": False,
            "is_translator": False,
            "is_translation_enabled": False,
            "profile_background_color": "F5F8FA",
            "profile_background_image_url": None,
            "profile_background_image_url_https": None,
            "profile_background_tile": False,
            "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
            "profile_link_color": "1DA1F2",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": True,
            "has_extended_profile": True,
            "default_profile": True,
            "default_profile_image": False,
            "following": None,
            "follow_request_sent": None,
            "notifications": None,
            "translator_type": "none"
        },
        "geo": None,
        "coordinates": None,
        "place": None,
        "contributors": None,
        "is_quote_status": False,
        "retweet_count": 0,
        "favorite_count": 0,
        "favorited": False,
        "retweeted": False,
        "lang": "fr"
    },
    {
        "created_at": "Sun Nov 29 22:17:59 +0000 2020",
        "id": 1333173388647403521,
        "id_str": "1333173388647403521",
        "full_text": "@KazuhikoSoma @CristobalSilvo @kiryucoco That's awesome.",
        "truncated": False,
        "display_text_range": [
            41,
            56
        ],
        "entities": {
            "hashtags": [],
            "symbols": [],
            "user_mentions": [
                {
                    "screen_name": "KazuhikoSoma",
                    "name": "HIATUS Kazuhiko Soma | 和彦そおま 💎",
                    "id": 1317711749387354114,
                    "id_str": "1317711749387354114",
                    "indices": [
                        0,
                        13
                    ]
                },
                {
                    "screen_name": "CristobalSilvo",
                    "name": "Cristóbal Silva",
                    "id": 4875476133,
                    "id_str": "4875476133",
                    "indices": [
                        14,
                        29
                    ]
                },
                {
                    "screen_name": "kiryucoco",
                    "name": "桐生ココ🐉@ホロライブ4期生",
                    "id": 1200397238788247552,
                    "id_str": "1200397238788247552",
                    "indices": [
                        30,
                        40
                    ]
                }
            ],
            "urls": []
        },
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
        "in_reply_to_status_id": 1332475325830361089,
        "in_reply_to_status_id_str": "1332475325830361089",
        "in_reply_to_user_id": 1317711749387354114,
        "in_reply_to_user_id_str": "1317711749387354114",
        "in_reply_to_screen_name": "KazuhikoSoma",
        "user": {
            "id": 1319269425522958336,
            "id_str": "1319269425522958336",
            "name": "Nickatak",
            "screen_name": "nickatak",
            "location": "",
            "description": "",
            "url": None,
            "entities": {
                "description": {
                    "urls": []
                }
            },
            "protected": False,
            "followers_count": 0,
            "friends_count": 5,
            "listed_count": 0,
            "created_at": "Thu Oct 22 13:28:42 +0000 2020",
            "favourites_count": 1,
            "utc_offset": None,
            "time_zone": None,
            "geo_enabled": False,
            "verified": False,
            "statuses_count": 14,
            "lang": None,
            "contributors_enabled": False,
            "is_translator": False,
            "is_translation_enabled": False,
            "profile_background_color": "F5F8FA",
            "profile_background_image_url": None,
            "profile_background_image_url_https": None,
            "profile_background_tile": False,
            "profile_image_url": "http://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/1333656414540034050/WBgFXJCd_normal.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1319269425522958336/1606803455",
            "profile_link_color": "1DA1F2",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": True,
            "has_extended_profile": True,
            "default_profile": True,
            "default_profile_image": False,
            "following": None,
            "follow_request_sent": None,
            "notifications": None,
            "translator_type": "none"
        },
        "geo": None,
        "coordinates": None,
        "place": None,
        "contributors": None,
        "is_quote_status": False,
        "retweet_count": 0,
        "favorite_count": 0,
        "favorited": False,
        "retweeted": False,
        "lang": "en"
    }
]